image: rust:1.81.0-slim-bookworm

.only_tag:
  rules:
    - if: $CI_COMMIT_TAG

.only_manual_tag:
  rules:
    - if: $CI_COMMIT_TAG
      when: manual

stages:
  - test
  - linter
  - publish

tests:
  stage: test
  script:
    - cargo test --all-targets

linter:clippy:
  stage: linter
  script:
    - rustup component add clippy
    - cargo clippy --lib --tests -- -D warnings


publish:
  stage: publish
  parallel:
    matrix:
      - PROJECT:
        - dto_mapper
        - dto_mapper_derive
  script:
    - cd $PROJECT
    - cargo publish
  extends:
    - .only_manual_tag
