image: rust:1.81.0-slim-bookworm

include:
  - project: "procivis/one/one-operations"
    file:
      - "gitlab/github.gitlab-ci.yml"

variables:
  GITHUB_PROJECT: "procivis/one-dto-mapper-rs"

.only_tag:
  rules:
    - if: $CI_COMMIT_TAG

.only_manual_tag:
  rules:
    - if: $CI_COMMIT_TAG
      when: manual

stages:
  - test
  - linter
  - github
  - publish

tests:
  stage: test
  script:
    - cargo test --all-targets

linter:clippy:
  stage: linter
  script:
    - rustup component add clippy
    - cargo clippy --lib --tests -- -D warnings

github:push:
  needs: []
  extends:
    - .github:push

github:release:
  extends:
    - .github:release
  needs:
    - job: github:push

publish:
  stage: publish
  needs:
    - job: github:push
  parallel:
    matrix:
      - PROJECT:
        - one-dto-mapper-derive
        - one-dto-mapper
  script:
    - cd $PROJECT
    - cargo publish
  extends:
    - .only_manual_tag
