image: rust:1.81.0-slim-bookworm

include:
  - project: "procivis/one/one-operations"
    file:
      - "gitlab/ci-tools.gitlab-ci.yml"

variables:
  GITHUB_TAG_PATTERN: /^v[0-9]+\.[0-9]+\.[0-9]+$/

.only_tag:
  rules:
    - if: $CI_COMMIT_TAG

.only_manual_tag:
  rules:
    - if: $CI_COMMIT_TAG
      when: manual

stages:
  - test
  - linter
  - github
  - publish
  - sync_with_jira

tests:
  stage: test
  script:
    - cargo test --all-targets

linter:clippy:
  stage: linter
  script:
    - rustup component add clippy
    - cargo clippy --lib --tests -- -D warnings

github:push:
  stage: github
  variables:
    GITHUB_PROJECT: "procivis/one-dto-mapper-rs"
    PROJECT: $CI_PROJECT_NAME
  extends:
    - .ci-tool:open_source_release

publish:
  stage: publish
  needs: []
  when: manual
  parallel:
    matrix:
      - PROJECT:
        - one-dto-mapper-derive
        - one-dto-mapper
  script:
    - cd $PROJECT
    - cargo publish
  rules:
    - if: $CI_COMMIT_TAG && $PROJECT == "one-dto-mapper"
      when: manual
      needs:
        - job: "publish: [one-dto-mapper-derive]"
    - if: $CI_COMMIT_TAG
      when: manual


set_jira_version:
  stage: sync_with_jira
  extends:
    - .ci-tool:set_jira_version
